### PR TITLE
Fix Nat -> Int parameters in Alive statements

### PR DESCRIPTION
**Pull request by goens**
Fix Nat -> Int parameters in Alive statements (making PR for CI)

### CODE REVIEW

**Comment by bollu** [comment]
LGTM, I'm assuming this is based off of https://github.com/bollu/alive/pull/2?

**Comment by bollu** [comment]
@goens May I merge this?

**Comment by goens** [comment]
@bollu there's a couple of changes missing I found while debugging this, I will push later tonight/tomorrow!

**Comment by tobiasgrosser** [comment]
If the changes in this PR are already an improvement, it might make sense to merge and then push the next batch of changes into another PR.

**Comment by goens** [comment]
this is also made obsolete by #49

**Pull request closed without merging**
