### PR TITLE
Tssa bottom up

### PR DESCRIPTION
**Pull request by tobiasgrosser**
On my machine this improves performance as follows:

```
0.4s alive_many_units                
4.4s alive_many_consts                
0.1s alive_fixed_size_integer                
0.0s alive_constant_fold_1                
2.9s alive_constant_fold_10                
4.9s alive_constant_fold_100 (timeout in elab)                
 
0.4s alive_many_units                
2.4s alive_many_consts                
0.1s alive_fixed_size_integer                
0.0s alive_constant_fold_1                
2.9s alive_constant_fold_10                
5.0s alive_constant_fold_100 (timeout in simp) 
```

### CODE REVIEW

**Comment by bollu** [comment]
Looks conceptually correct to me. I didn't check the elaboration too closely, but I'm going to assume it's correct. LGTM!

**Comment by bollu** [comment]
For some context, I got tired writing in ANF/SSA form, so I wrote a version that lets one mix expression syntax and SSA syntax. The intermediate variables are translated to temporaries. I'll refactor the code and unify uses of EDSL/EDSL2 later in the week(end).

**Comment by bollu** [comment]
@tobiasgrosser can you explain the performance improvement?

**Comment by bollu** [comment]
(AFAIK, the cost of composing continuations ala [`DList`](https://wiki.haskell.org/Difference_list) should be asymptotically the same as building bottom-up. Is the difference in the constant factors, then?

**Comment by tobiasgrosser** [comment]
No, I cannot explain the performance improvements. Would be curious to learn where they come from, though.

**Pull request merged**
