### PR TITLE
Option bitvec

### PR DESCRIPTION
**Pull request by goens**
Push the `Option` into the denotation of the UserType for UB in Alive

### CODE REVIEW

**Comment by goens** [comment]
@bollu I feel there's going to be some Kleisli whatnot names for the functions I added in `Util`, maybe you can suggest the proper names for them :)

**Comment by bollu** [comment]
@goens don't know the name, we would call it `liftA2 (,)` or `liftA3 (,,)`, wouldn't give them names :D

**Comment by goens** [comment]
@bollu so are you fine with the current names? Or should we rename them (and what about `pairBind`)? does the rest look okay to you?

**Comment by bollu** [comment]
I am happy with the current names :)

**Comment by bollu** [comment]
@goens Can we refactor `(fun x y => (x == y) ::ᵥ Vector.nil)` and similar into a common function `Bool.toBitVector: Bool -> Bitvec`

**Comment by goens** [comment]
@bollu I'll do you one better and just use `Coe`s :)

**Pull request merged**
