### PR TITLE
Simp mlir

### PR DESCRIPTION
**Pull request by goens**
Just add the `simp_mlir` macro as we describe it in the paper. @bollu are you okay with us merging this?

### CODE REVIEW

**Comment by bollu** [comment]
@goens I would prefer the issue mentioned in the tactic (the resolution of `TypedUserSemantics`) works well. I'd personally only feel comfortable changing the statement in the paper from pink to black if the tactic lived in `Core/` and was used everywhere in each `Project` to simplify the semantics

**Comment by goens** [comment]
okay... I don't feel like it's a big issue at all, but I'll get that to work then I guess.

**Comment by bollu** [comment]
@goens I pushed to `simp_mlir` just now to unintroduce the `TUSInstance` typeclass. I do not see why it is necessary here for the tactic. The refactored code `simp_mlir`'s correctly.

**Comment by bollu** [comment]
Review requested, @goens

**Comment by goens** [comment]
@bollu I'm surprised that this just works (not at the computer right now), did you test this, does it reduce all the alive cases?

**Comment by bollu** [comment]
@goens locally, the build is green, which means that the tactic reduces the examples correctly, since our file has `simp_mlir` followed by the "pure math theorem" application.

**Comment by goens** [comment]
cool! I think I missed the general `TypedUserSemantics` addition to the `simp` set, that does make sense! Are we happy to merge this @bollu? (I don't want to merge my own PR)

**Pull request merged**
